service: enigma-trade
frameworkVersion: '2'

custom:
  settings:
    USER_INFO_TABLE: users

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment: ${self:custom.settings}
  iamRoleStatements: 

functions:
  hello:
    handler: handler.hello
